dist: trusty
sudo: required

language: go
go:
  - 1.7.1
    
go_import_path: github.com/sunyuan3/just_for_test

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq autoconf automake

install:
  - cd ${TRAVIS_BUILD_DIR}
  - echo "hello yile"

script:
  - cd ${TRAVIS_BUILD_DIR} && echo "goodbye yile"
